apiVersion: v1
kind: ConfigMap
metadata:
  name: mastodon-config
data:
  REDIS_HOST: mastodon-redis-service
  REDIS_PORT: "6379"
  DB_HOST: postgres.ocf.berkeley.edu
  DB_USER: ocfmastodon
  DB_NAME: ocfmastodon
  DB_PORT: "5432"
  PGSSLMODE: require
  LOCAL_DOMAIN: ocf.berkeley.edu
  WEB_DOMAIN: mastodon.ocf.berkeley.edu
  SMTP_SERVER: smtp.ocf.berkeley.edu
  SMTP_PORT: "25"
  SMTP_AUTH_METHOD: none
  SMTP_FROM_ADDRESS: ocfmastodon@ocf.berkeley.edu
  SMTP_OPENSSL_VERIFY_MODE: none
  EMAIL_DOMAIN_WHITELIST: ocf.berkeley.edu
  SAML_ENABLED: true
  SAML_ACS_URL: https://mastodon.ocf.berkeley.edu/auth/auth/saml/callback
  SAML_ISSUER: mastodon
  SAML_IDP_SSO_TARGET_URL: https://auth.ocf.berkeley.edu/auth/realms/ocf/protocol/saml
  SAML_IDP_CERT: "-----BEGIN CERTIFICATE-----\nMIIClTCCAX0CBgFrWCaGbjANBgkqhkiG9w0BAQsFADAOMQwwCgYDVQQDDANPQ0YwHhcNMTkwNjE0MjIzOTA4WhcNMjkwNjE0MjI0MDQ4WjAOMQwwCgYDVQQDDANPQ0YwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCZic2k64Nljah1y1qVbWn87VWp9VyXSkX+FJPZJVK3QjtLRLppQZV107VJ6P7zh9GwSxWOZqT3K6S4dATPqZM1OCowGzurryfeB9fs4cYyNTC4z7JjAvs0P1RsMKyQkRVevF7k2QjVBfTTGg6y27lCCFUyfsknx7/qabFQsPxinfQKSDBus+Epf1WcRHKmvBYYARDkTt0hsQ4B2EL+9PUHrXh80Ss6DjvYpUuaaBRcR2pZEaN9Fa5aH9n6m8KxmLhguODgoFZwrpJcujkePD+oW7NMMx6wO0SzVyKEIpdBPeFprUMXlq5LwBbEcGWYT3yEfkYTFlEu8qvqPObrvohNAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAG0NG14VMoGLPELaQv8Dqch9BKW/6pmX5FwQF/siVc9fK9hhKxDjpnDHLJD8/s2VcOiSQo66kF/Mo6Agp4LR/FglNjOXjQnM+9XXROFbHpPXbRPswxjgGQb00UTwAw2KB8X9gpiVEKNnPUjQyj6doKlKpPbFutTdCAjupu4bWhZJc5m/H2ui8ImYed5OPrEN1HfUIwPzndqPEsxLRnpPU/TPfTHIhvDXtMWgeQtXt5EZb71SGIYpJzxM9gPtH2DMtAo6GfaoX2tiuafmly4QQkWs7qfMeOcPjqCvj9bbwxiMfe2f0UsxYBPowvD8a8FXnJe0C8YXpkcvyOWzGsTbA/Y=\n-----END CERTIFICATE-----"
  SAML_NAME_IDENTIFIER_FORMAT: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
  SAML_SECURITY_WANT_ASSERTION_SIGNED: true
  SAML_SECURITY_WANT_ASSERTION_ENCRYPTED: true
  SAML_SECURITY_ASSUME_EMAIL_IS_VERIFIED: true
  
